version: '3'

services:
  server:
    build:
      context: .
      target: server
    ports:
      - "5000:5000"
    depends_on:
      - database

  client:
    build:
      context: .
      target: client
    ports:
      - "3000:3000"
    depends_on:
      - server

  database:
    build:
      context: .
      target: database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  pgadmin:
    build:
      context: .
      target: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database
